### ISSUE TITLE
status of the org

### ISSUE THREAD

**Issue by Roger-luo** [JuliaQuantum/JuliaQuantum.github.io#47]
I'm not sure how many people is left... Is [QuDirac.jl](https://github.com/JuliaQuantum/QuDirac.jl) and [QuDynamics.jl](https://github.com/JuliaQuantum/QuDynamics.jl) still under maintenance? Are your guys still going to update them? @jrevels  @amitjamadagni 

And I'm wondering if @cgranade is still working on that QInfer wrapper according to [news](http://juliaquantum.github.io/news/2017/04/qinfer-got-a-julia-interface)? I didn't see any new repository for this and it has been a year...

For myself, I won't work on [QuCmp.jl](https://github.com/JuliaQuantum/QuCmp.jl) any more, since we have got [Yao.jl](https://github.com/QuantumBFS/Yao.jl) and I do not have further access to this org.

Julia is already 1.0, and waiting for 1.0 is not always a good reason... Most of the packages are in v0.5 or even older here.

If nobody is working on any projects in the org and if there is only website updates, I don't think the org should appear on Julia's official website [julialang.org/community](https://julialang.org/community/), which will lead fresh Julians to the wrong place. There are plenty of active project for quantum physics on GitHub in Julia at the moment, as there will be more as far as I know.

Bests,
Roger

**Comment by jrevels** [comment]
I agree completely. Nothing here is maintained/being developed at all AFAIK.

I think we should archive all the packages here (i.e. move them to https://github.com/JuliaArchive), and probably shut down or heavily edit the JuliaQuantum site since it probably just confuses people by hyping unmaintained code.

I don't have to bandwidth to really do much, but I can handle just moving the packages over to JuliaArchive if others agree.

**Comment by Roger-luo** [comment]
It looks like nobody replied... I'll delete JuliaQuantum in julialang.org first.

**Comment by i2000s** [comment]
@roger-luo I have emailed @revels earlier that I will update all JuliaQuantum packages one by one later for the Julia v1.0 release and organize some discussions for our org. Please give me some time for the PRs. I am on academic traveling to give talks and for collaborations--Chengdu from today to Aug 15, then Shanghai until 25th, and hopefully finally settle down at Hangzhou, China. I will try my best to revive the org, as one of the co-founders. Thanks.

**Comment by jrevels** [comment]
I'm going to fully deprecate the two packages that I've chiefly worked on, QuDirac.jl and QuBase.jl. 

QuDirac.jl as an idea could still be useful, but it's implementation would need a total redesign in order to actually be usable by people (it should be a DSL that stages computations for one of the existing tensor compiler packages), so it can't simply be updated. If anyone ever wants to continue work in that vein, they should do so under a new package with a new name.

QuBase.jl never even finished for an initial release, so it too cannot simply be updated, and any future work should just be done under a new package with a new name. Most of the Julia ecosystem is moving away from the idea of having heavy `*Base.jl`-style packages anyway.

@i2000s Feel free to to do what you want, no offense intended. My choices here are purely technical. 

I do think the website should be removed or at least toned down a bit until there are some actual implementations here that are useable with current versions of Julia.

**Comment by acroy** [comment]
Well, I think @jrevels is basically (and unfortunately) right. When we founded JuliaQuantum and QuBase, QuDynamics etc we wanted to create something that can be used by everyone doing something „quantum”. Apparently there has been no (deeper) interest or no need because otherwise people would have found their way to JuliaQuantum. This did not happen as far as I can see.

I would also think that the packages (Qu*) should be depricated unless someone steps up to actively maintain them. Some ideas are still good, but it is probably easier to start from square one. The website etc can be useful as a central to reflect activities around quantum information et al, but I would suggest to organize it more as an open community - if there is actually some interest.

**Comment by i2000s** [comment]
@jrevels @acroy I need to catch up now. Could we find a time to chat on [Gitter](https://gitter.im/JuliaQuantum/JuliaQuantum.github.io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). ***Between ~8pm to 10pm on Aug 13, Beijing Time,*** should work for me at the closest time slot. ***How about you?*** Of course, everyone is welcome to participate. 

I agree with you @acroy that we should serve as an open community--to my understanding--to help grow the connections among Julians for quantum information etc., as a platform to provide opportunities, and as a hub for discussions and collaborations across disciplines that were once suggested by @Jutho . Wherever packages/libraries are hosted, as long as they are related to quantum in Julia, we should offer our platform for them to grow and coordinate among related activities. I am no longer restricted to closed-source development related to my studies nowadays and am happy to share my thoughts exchanged with people I visited in the past month and catch up with people who are still interested in working together as an entity. The website can be and should be updated after a firm discussion ASAP to reflect the changes.

**Comment by Roger-luo** [comment]
Just some comments, and maybe suggestion if someone really want to make this org living. First thing is, a GitHub org is for people cooperating on practical, technical projects, and even because of the flexible development, there is no document at first but only recently instant massages, rather than writing long documents.

No offense, but after 2 or 3 years I don't see any solid project was living in this org. This is not @jrevels or @acroy 's problem, their other projects are kept running. Open source should be open. I don't feel open with so many documents and roadmaps. We are here to develop tools for quantum physics rather than reading the documents. Who is the co-founder is not important, what is the agreement is not important, this is not writing an paper, or doing something political, I'm quite disappointed that a promising org is dead, and people have to work in separated org like QuanutmOptics, QuantumBFS, etc.

Before writing a website and long documents, there should be a **solid, practical project** written in Julia first. And that is why I don't want to move Yao.jl to JuliaQuantum. And I believe that's why no more people was attracted to this org. @acroy 's Expokit.jl is useful and solid and it attracts people
 (like our team, @GiggleLiu is helping in improving it).  In my mind, A co-founder in open source community does not mean writing website and documents, it means one of the projects is written by you.

And please understand, I also hope Julia is able to have a org named after it with Quantum, but I don't want people complain Julians are not solid, either. I hoped this org could be something great and I tried but not any more with a PR not merged after 2 years. 

To be honest, QuCmp.jl could be something like ProjectQ when it was started. And that was what in my mind. And that's why we have Yao.jl later. I will delete this org from the official website first, and maybe you can add it back when those projects were updated and functional later. Since @jrevels have put them in Archive. I insist, because I want to see some good changes. People are trying to be polite, but that won't solve the problem. I believe if Linus (the father of Linux) is here, he will say something, and that is why I'm writing all these things. 

@garrison have complained about this politely a long time ago when I was still an undergrad. And nothing changed. How many things have been done in the roadmap until then? This is definitely not because the instability of Julia. Technically, we have Compat.jl and many more.

I'm looking forward to the future. I guess I'm not the only one thinking about it. TALK IS CHEAP, SHOW ME THE CODE. If you want to save the org, update them first, or write something practical in Julia first.

Sorry, but I have to be rude here. Just want to make things better. I will close this, since apparently nobody is going to work in this org.

Bests,
Roger
